[package]
name = "crudcodegen"
version = "0.1.0"
authors = ["Wouter Nederhof <wouternederhof@MacBook-Air-van-Wouter.local>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
