spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:15432/postgres
  username: postgres
  password: postgres

graphql.servlet.websocket.enabled: false

security:
  jwt-secret: this-needs-to-be-changed
  jwt-issuer: this-needs-to-be-changed
