name: Build
on:
  push:
    branches:
      - main
    tags:
      - "v*"
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build -ldflags "-s -w" crudcodegen/cmd/crudcodegen
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          title: "${{ steps.vars.outputs.tag }}-${{ matrix.os }}"
          files: |
            LICENSE.md
            crudcodegen*
