name: Build and test Go
on: [ push, pull_request ]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - uses: docker-practice/actions-setup-docker@master
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build -ldflags "-s -w" crudcodegen/cmd/crudcodegen
      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v ./...
      - uses: actions/upload-artifact@v2
        with:
          name: CrudCodeGen ${{ matrix.os }}
          path: crudcodegen*
