name: native-image-compile
on: [push]
jobs:
  native-image-compile-in-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      - run: ./mvnw spring-boot:build-image
